version: 2
jobs:
  build:
    docker:
      - image: circleci/node:<NODE_VERSION>
      - image: mongo:<MONGO_VERSION>
    environment:
      NODE_ENV: test
      MONGO_HOST: <MONGO_HOST>
      MONGO_PORT: <MONGO_PORT>
      MONGO_DB: <DB_NAME>
      SSH_HOST: <SSH_HOST>
      SSH_USER: <SSH_USER>

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5 mocha'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  deploy:    
    environment:
      SSH_HOST: <SSH_HOST>
      SSH_USER: <SSH_USER>
      DEPLOY_FOLDER_PATH: <DEPLOY_FOLDER_PATH>
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - <fingerprints>
      - run:
          name: Deploy 
          command: |
            ssh $SSH_USER@$SSH_HOST "source /etc/profile; cd $DEPLOY_FOLDER_PATH; npm run deploy"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build   
          filters: 
            branches:
              only: master